input_string = input("Введите строку: ")
count_r = input_string.count("r")
count_t = input_string.count("t")
print("Количество букв 'r' в строке:", count_r)
print("Количество букв 't' в строке:", count_t)